#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""SK -> CZ prekladač pre endovaskulárne nástroje.
Pravidlo bezpečnosti: meníme len reťazce so slovenskou diakritikou / tvarmi.
Názvy stĺpcov a kódové hodnoty sú ASCII (komplikacie_struct, fem, M, vlastny)
-> tie sa nezhodujú s našimi vzormi a ostávajú nedotknuté.
Frázy sú zoradené od najdlhších, aby nedošlo k čiastočným kolíziám.
"""
import sys

PAIRS = [
    # --- viacslovné frázy najprv ---
    ("bez závažnej stenózy", "bez závažné stenózy"),
    ("bez revaskularizácie", "bez revaskularizace"),
    ("Kontrastná látka", "Kontrastní látka"),
    ("kontrastná látka", "kontrastní látka"),
    ("Technický úspech", "Technický úspěch"),
    ("technický úspech", "technický úspěch"),
    ("Manuálna kompresia", "Manuální komprese"),
    ("manuálna kompresia", "manuální komprese"),
    ("Priemer × Dĺžka", "Průměr × Délka"),
    ("Dĺžka lézie", "Délka léze"),
    ("Charakteristika krčka", "Charakteristika krčku"),
    ("Distálna landing", "Distální landing"),
    ("Distálna emboloprotekccia", "Distální emboloprotekce"),
    ("Distálna emboloprotekcia", "Distální emboloprotekce"),
    ("Infrarenálna angulácia", "Infrarenální angulace"),
    ("Suprarenálna angulácia", "Suprarenální angulace"),
    ("Priemer krčka proximálny", "Průměr krčku proximální"),
    ("Priemer vaku", "Průměr vaku"),
    ("Dĺžka krčka", "Délka krčku"),
    ("Vhodnosť podľa IFU", "Vhodnost dle IFU"),
    ("mimo IFU (hostile neck)", "mimo IFU (hostile neck)"),
    ("Tvar krčka", "Tvar krčku"),
    ("Kalcifikácia krčka", "Kalcifikace krčku"),
    ("Trombus v krčku", "Trombus v krčku"),
    ("reverzne kónický", "reverzně kónický"),
    ("Domodelovanie tela SG", "Domodelování těla SG"),
    ("Domodelovanie extenzií", "Domodelování extenzí"),
    ("domodelovanie", "domodelování"),
    ("Domodelovanie", "Domodelování"),
    ("Pridať extenziu", "Přidat extenzi"),
    ("Pridať stent", "Přidat stent"),
    ("Pridať balón", "Přidat balón"),
    ("Pridať", "Přidat"),
    ("Výsledný angiografický obraz", "Výsledný angiografický obraz"),
    ("Výsledný obraz", "Výsledný obraz"),
    ("Výsledok", "Výsledek"),
    ("výsledok", "výsledek"),
    ("Vygenerovať nález", "Vygenerovat nález"),
    ("Vygenerovať", "Vygenerovat"),
    ("Skopírovať", "Zkopírovat"),
    ("Kopírovať", "Kopírovat"),
    ("Skopírované!", "Zkopírováno!"),
    ("Pohlavie", "Pohlaví"),
    ("Anestézia", "Anestezie"),
    ("anestézia", "anestezie"),
    ("Riečisko", "Řečiště"),
    ("riečisko", "řečiště"),
    ("Komplikácie", "Komplikace"),
    ("komplikácie", "komplikace"),
    ("Komorbidity", "Komorbidity"),
    ("Antitrombotiká", "Antitrombotika"),
    ("antitrombotiká", "antitrombotika"),
    ("Prístup", "Přístup"),
    ("prístup", "přístup"),
    ("Uzáver", "Uzávěr"),
    ("uzáver", "uzávěr"),
    ("Záver", "Závěr"),
    ("záver", "závěr"),
    ("Navádzanie", "Navádění"),
    ("navádzanie", "navádění"),
    ("Spôsob", "Způsob"),
    ("spôsob", "způsob"),
    ("Smer", "Směr"),
    ("Dĺžka", "Délka"),
    ("dĺžka", "délka"),
    ("Priemer", "Průměr"),
    ("priemer", "průměr"),
    ("Kompresia", "Komprese"),
    ("kompresia", "komprese"),
    ("Závažnosť", "Závažnost"),
    ("závažnosť", "závažnost"),
    ("Lokalizácia", "Lokalizace"),
    ("lokalizácia", "lokalizace"),
    ("Indikácia", "Indikace"),
    ("indikácia", "indikace"),
    ("Diagnóza", "Diagnóza"),
    ("Štúdia", "Studie"),
    ("štúdia", "studie"),
    ("Dátum", "Datum"),
    ("Operatér", "Operatér"),
    ("Lekári", "Lékaři"),
    ("Zabezpečenie", "Zabezpečení"),
    ("Punkcia", "Punkce"),
    ("punkcia", "punkce"),
    ("Manuálna", "Manuální"),
    ("manuálna", "manuální"),
    ("Konverzia", "Konverze"),
    ("Stentgraft (telo)", "Stentgraft (tělo)"),
    ("telo stentgraftu", "tělo stentgraftu"),
    ("tela stentgraftu", "těla stentgraftu"),
    ("Charakteristika", "Charakteristika"),
    ("Krehký/á", "Křehký/á"),
    ("Symptomatický", "Symptomatický"),
    ("Polymorbidný", "Polymorbidní"),
    ("liekový (DES)", "lékový (DES)"),
    ("samoexpandibilný", "samoexpandibilní"),
    ("balónexpandibilný", "balónexpandibilní"),
    ("vlastný popis", "vlastní popis"),
    ("vlastný", "vlastní"),
    ("Vlastný", "Vlastní"),
    ("Ukladám...", "Ukládám..."),
    ("Načítavam", "Načítám"),
    ("Uložiť", "Uložit"),
    ("Uložené", "Uloženo"),
    ("Strana", "Strana"),
    ("Tepna", "Tepna"),
    ("Segment", "Segment"),
    ("predilatácia", "predilatace"),
    ("Predilatácia", "Predilatace"),
    ("postdilatácia", "postdilatace"),
    ("Aterektómia", "Aterektomie"),
    ("aterektómia", "aterektomie"),
    ("Trombektómia", "Trombektomie"),
    ("trombektómia", "trombektomie"),
    ("Reentry katéter", "Reentry katétr"),
    ("katéter", "katétr"),
    ("Katéter", "Katétr"),
    ("Vek", "Věk"),
    ("rotačná", "rotační"),
    ("Rotačná", "Rotační"),
    ("Aspiračná", "Aspirační"),
    ("aspiračná", "aspirační"),
    ("Veľkosť", "Velikost"),
    ("veľkosť", "velikost"),
    ("Značka", "Značka"),
    ("Hodnotenie", "Hodnocení"),
    ("Prihlásenie", "Přihlášení"),
    ("zber pre štúdiu", "sběr pro studii"),
    ("Diaľka", "Délka"),
    # --- batch 2: klinické termíny a naratív ---
    ("Liečba", "Léčba"), ("liečbe", "léčbě"), ("liečby", "léčby"), ("liečba", "léčba"),
    ("Akútna", "Akutní"), ("akútna", "akutní"), ("Akútne", "Akutní"), ("akútne", "akutní"),
    ("Urgentná", "Urgentní"), ("Urgentný", "Urgentní"), ("urgentnému", "urgentnímu"), ("Elektívny", "Elektivní"), ("elektívnemu", "elektivnímu"),
    ("Krvácanie", "Krvácení"), ("krvácanie", "krvácení"),
    ("Diéta", "Dieta"), ("diétou", "dietou"),
    ("Fajčiar", "Kuřák"), ("fajčiar", "kuřák"),
    ("Názov", "Název"), ("názov", "název"),
    ("Odporúčame", "Doporučujeme"), ("Odporúčanie", "Doporučení"), ("odporúčanie", "doporučení"),
    ("Doplňujúce", "Doplňující"), ("doplňte", "doplňte"),
    ("Hlavné", "Hlavní"), ("hlavné", "hlavní"), ("Ostatné", "Ostatní"), ("ostatné", "ostatní"),
    ("Spustiť", "Spustit"), ("Otestovať", "Otestovat"), ("Nasadiť", "Nasadit"), ("Vybrať", "Vybrat"), ("vybrať", "vybrat"),
    ("Voľný", "Volný"), ("voľný", "volný"),
    ("Vzhľadom", "Vzhledem"), ("Väčšia", "Větší"), ("Menšia", "Menší"),
    ("Ľahká", "Lehká"), ("Ťažká", "Těžká"), ("Stredná", "Střední"), ("stredný", "střední"),
    ("Žiadne", "Žádné"), ("žiadne", "žádné"), ("žiadna", "žádná"), ("žiadny", "žádný"), ("Žiadna", "Žádná"),
    ("Ďalšie", "Další"), ("Ďalší", "Další"), ("ďalší", "další"), ("ďalšom", "dalším"),
    ("Ľavá", "Levá"), ("ľavej", "levé"), ("Vľavo", "Vlevo"), ("vľavo", "vlevo"),
    ("Zľava", "Zleva"), ("Sprava", "Zprava"), ("Obojstranne", "Oboustranně"),
    ("Bilaterálne", "Bilaterálně"), ("Bilaterálna", "Bilaterální"),
    ("Všetky", "Všechny"), ("Všetko", "Všechno"),
    ("Úmrtie", "Úmrtí"), ("úmrtie", "úmrtí"),
    ("Konzervatívne", "Konzervativní"), ("konzervatívne", "konzervativní"), ("Konzervatívny", "Konzervativní"), ("konzervatívny", "konzervativní"),
    ("Kombinácia", "Kombinace"), ("kombináciou", "kombinací"), ("Trojkombinácia", "Trojkombinace"), ("trojkombinácia", "trojkombinace"),
    ("Distálna", "Distální"), ("distálna", "distální"), ("distálnej", "distální"), ("distálny", "distální"), ("distálnu", "distální"),
    ("Proximálny", "Proximální"), ("proximálny", "proximální"),
    ("Panvové", "Pánevní"), ("panvové", "pánevní"), ("panvových", "pánevních"),
    ("Stabilná", "Stabilní"), ("stabilná", "stabilní"), ("Nestabilná", "Nestabilní"), ("nestabilná", "nestabilní"),
    ("Materiály", "Materiály"), ("materiálov", "materiálů"),
    ("Rozšírenia", "Rozšíření"),
    ("Identifikácia", "Identifikace"),
    ("Implantácia", "Implantace"), ("implantácia", "implantace"), ("implantácii", "implantaci"),
    ("Katetrizácia", "Katetrizace"), ("Kalibrácia", "Kalibrace"), ("Migrácia", "Migrace"), ("migrácia", "migrace"),
    ("Ruptúra", "Ruptura"), ("ruptúra", "ruptura"),
    ("Oklúzia", "Okluze"), ("oklúzia", "okluze"),
    ("Hematóm", "Hematom"), ("hematóm", "hematom"),
    ("Embolizácia", "Embolizace"), ("embolizácia", "embolizace"), ("embolizácie", "embolizace"),
    ("ischémia", "ischemie"), ("ischémii", "ischemii"),
    ("renálna", "renální"), ("renálnej", "renální"), ("renálnych", "renálních"), ("renálne", "renální"),
    ("kreatinín", "kreatinin"),
    ("Krehký/á", "Křehký/á"), ("krehký", "křehký"), ("krehká", "křehká"),
    ("Polymorbidný", "Polymorbidní"), ("polymorbidný", "polymorbidní"), ("polymorbidná", "polymorbidní"),
    ("Unilaterálny", "Unilaterální"), ("unilaterálneho", "unilaterálního"),
    ("Bifurkačný", "Bifurkační"), ("bifurkačného", "bifurkačního"),
    ("Akcesórna", "Akcesorní"), ("akcesórnej", "akcesorní"),
    ("Vertebrálny", "Vertebrální"), ("Vertebrálnym", "Vertebrálním"),
    ("Doplňujúce", "Doplňující"),
    ("Amputácia", "Amputace"), ("amputácia", "amputace"),
    ("Perforácia", "Perforace"), ("perforácia", "perforace"),
    ("Trombóza", "Trombóza"), ("Dilatácia", "Dilatace"), ("dilatácia", "dilatace"),
    ("Inflácia", "Inflace"), ("inflácia", "inflace"),
    ("Rekanalizácia", "Rekanalizace"), ("rekanalizácia", "rekanalizace"),
    ("Restenóza", "Restenóza"), ("restenóza", "restenóza"),
    ("Komplikácií", "Komplikací"), ("komplikácií", "komplikací"), ("komplikácii", "komplikaci"),
    ("Poznámka", "Poznámka"),
    ("Časový", "Časový"),
    ("kritická", "kritická"), ("Kritické", "Kritické"),
    ("Štruktúrovaný", "Strukturovaný"), ("štatistík", "statistik"), ("štatistiku", "statistiku"),
    ("publikačnú", "publikační"), ("publikácie", "publikace"),
    ("periprocedurálne", "periprocedurální"),
    ("Črevná", "Střevní"), ("črevná", "střevní"),
    ("Štandardná", "Standardní"), ("súdkovitý", "soudkovitý"),
    # --- naratív (slovesá) ---
    ("Zavádzame", "Zavádíme"), ("zavádzame", "zavádíme"),
    ("Uzatvárame", "Uzavíráme"), ("uzatvárame", "uzavíráme"),
    ("vymieňame", "vyměňujeme"), ("Vymieňame", "Vyměňujeme"),
    ("prechádzame", "procházíme"), ("Prechádzame", "Procházíme"),
    ("Zabezpečujeme", "Zajišťujeme"), ("zabezpečujeme", "zajišťujeme"),
    ("Zabezpečenie", "Zajištění"), ("zabezpečenia", "zajištění"),
    ("dosiahnutá", "dosažena"), ("dosiahnutý", "dosažen"),
    ("Nasadený", "Nasazen"), ("nasadený", "nasazen"),
    ("Vykonaná", "Provedena"), ("vykonaná", "provedena"),
    ("Tlač", "Tisk"),
    ("Vyplňte", "Vyplňte"), ("vyplňte", "vyplňte"),
    ("Označte", "Označte"),
    ("Sérový", "Sérový"), ("kľudová", "klidová"), ("bolesť", "bolest"),
    ("končatiny", "končetiny"), ("brušné", "břišní"),
]


def main():
    for path in sys.argv[1:]:
        with open(path, encoding="utf-8") as f:
            txt = f.read()
        for sk, cz in PAIRS:
            txt = txt.replace(sk, cz)
        with open(path, "w", encoding="utf-8") as f:
            f.write(txt)
        print("translated:", path)


if __name__ == "__main__":
    main()
